osx_image: xcode9
language: objective-c
notifications:
  email: false
script: 
  - set -o pipefail && xcodebuild -workspace 'RxAlamofire/RxAlamofire.xcworkspace' -scheme 'RxAlamofireTests' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='11.0',name='iPhone 8' build test  | xcpretty -c --test

